name: Build and Deploy to Azure Web App from dev branch

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login backendchat.azurecr.io -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t backendchat.azurecr.io/chatapp:latest .

      - name: Push Docker image
        run: docker push backendchat.azurecr.io/chatapp:latest

      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v2
        with:
          app-name: chatapp-backend   
          images: backendchat.azurecr.io/chatapp:latest
